name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies (Cypress + static server + Netlify CLI)
      - name: Install dependencies
        run: |
          npm install --save-dev cypress http-server netlify-cli

      # Start static server (repo root -> http://localhost:8080)
      - name: Start server
        run: npx http-server . -p 8080 &

      # Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          install: false
          record: false
        env:
          CYPRESS_login_email: ${{ secrets.CYPRESS_LOGIN_EMAIL }}
          CYPRESS_login_password: ${{ secrets.CYPRESS_LOGIN_PASSWORD }}
          CYPRESS_baseUrl: "http://localhost:8080"

      # Upload Cypress artifacts (screenshots, videos, reports)
      - name: Upload Cypress artifacts
        if: always()   # ensures upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            cypress/reports

      # Deploy to Netlify (only if Cypress tests pass)
      - name: Deploy to Netlify
        if: success()   # ✅ runs only if all previous steps passed
        run: |
          npx netlify deploy --prod --dir=./ --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --yes
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}